import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google"; // Correctly import Manrope
import "./globals.css";

// Import the fonts
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const manrope = Manrope({
	variable: "--font-manrope", // Font variable for Manrope
	subsets: ["latin"],
	weight: ["300", "400", "600", "800"], // You can specify the weights you need
});

export const metadata: Metadata = {
	title: "Eugenio Poccia",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`} // Add the Manrope variable
			>
				{children}
			</body>
		</html>
	);
}
