import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import { AppContextProvider } from "../contexts/AppContext";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const manrope = Manrope({
	variable: "--font-manrope",
	subsets: ["latin"],
	weight: ["300", "400", "600", "800"],
});

export const metadata: Metadata = {
	title: "Eugenio Poccia",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AppContextProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}
					style={{
						maxWidth: "1440px",
						letterSpacing: "0.8px",
					}}
				>
					{children}
				</body>
			</AppContextProvider>
		</html>
	);
}
